import type { PresetsInfo } from './schema-parser.js';

const DIR_CONTEXT: Record<string, string> = {
  sections: '{ section: { settings: args } }',
  blocks:   '{ block: { settings: args } }',
  snippets: 'args',
};

const escQ = (s: string) => s.replace(/\\/g, '\\\\').replace(/'/g, "\\'");

export function buildAutoTitle(dir: string, filename: string): string {
  const base = filename.replace(/\.liquid$/, '');
  return dir.charAt(0).toUpperCase() + dir.slice(1) + '/' +
    base.replace(/-/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase());
}

function toExportName(name: string): string {
  const identifier = name
    .replace(/[^a-zA-Z0-9 ]/g, '')
    .split(/\s+/)
    .filter(Boolean)
    .map(w => w.charAt(0).toUpperCase() + w.slice(1))
    .join('');
  return /^\d/.test(identifier) ? `_${identifier}` : identifier || 'Default';
}

export function buildAutoStory(
  dir: string,
  filename: string,
  liquidRelPath: string,
  defaults: Record<string, unknown>,
  presetsInfo: PresetsInfo | null
): string {
  const title = buildAutoTitle(dir, filename);
  const hasDefaults = Object.keys(defaults).length > 0;
  const argsBlock = hasDefaults
    ? `  args: ${JSON.stringify(defaults, null, 2).replace(/\n/g, '\n  ')},\n`
    : '';

  if (!presetsInfo) {
    const context = DIR_CONTEXT[dir] ?? 'args';
    return [
      `// Auto-generated by storybook-shopify`,
      `import { renderTemplate } from 'storybook-shopify';`,
      `import template from '${escQ(liquidRelPath)}';`,
      ``,
      `export default {`,
      `  title: '${escQ(title)}',`,
      `  component: template,`,
      `  render: (args) => renderTemplate(template, ${context}),`,
      argsBlock + `};`,
      ``,
      `export const Default = {};`,
      ``,
    ].join('\n');
  }

  const { presets, hasBlocks } = presetsInfo;

  if (!presets.length) {
    const context = DIR_CONTEXT[dir] ?? 'args';
    return [
      `// Auto-generated by storybook-shopify`,
      `import { renderTemplate } from 'storybook-shopify';`,
      `import template from '${escQ(liquidRelPath)}';`,
      ``,
      `export default {`,
      `  title: '${escQ(title)}',`,
      `  component: template,`,
      `  render: (args) => renderTemplate(template, ${context}),`,
      argsBlock + `};`,
      ``,
      `export const Default = {};`,
      ``,
    ].join('\n');
  }

  const renderFn = hasBlocks
    ? `(args) => { const { blocks = [], ...settings } = args; return renderTemplate(template, { section: { settings, blocks } }); }`
    : `(args) => renderTemplate(template, { section: { settings: args } })`;

  const storyExports = presets.map(preset => {
    const exportName = toExportName(preset.name);
    const presetArgs: Record<string, unknown> = {};
    if (preset.blocks?.length) presetArgs.blocks = preset.blocks;
    const hasPresetArgs = Object.keys(presetArgs).length > 0;
    return [
      `export const ${exportName} = {`,
      `  name: '${escQ(preset.name)}',`,
      ...(hasPresetArgs
        ? [`  args: ${JSON.stringify(presetArgs, null, 2).replace(/\n/g, '\n  ')},`]
        : []),
      `};`,
    ].join('\n');
  });

  return [
    `// Auto-generated by storybook-shopify`,
    `import { renderTemplate } from 'storybook-shopify';`,
    `import template from '${escQ(liquidRelPath)}';`,
    ``,
    `export default {`,
    `  title: '${escQ(title)}',`,
    `  component: template,`,
    `  render: ${renderFn},`,
    argsBlock + `};`,
    ``,
    storyExports.join('\n\n'),
    ``,
  ].join('\n');
}
