[environments.development]
store = "ss-dev-1"
theme = "142425194580"
allow-live = true
ignore = [
  "templates/*.json",
  "templates/**/*.json",
  "sections/*.json",
  "config/settings_data.json",
  "locales/*",
]

