// Auto-generated by storybook-shopify
import { renderTemplate } from "storybook-shopify"
import template from "../sections/announcement-bar.liquid"

export default {
  title: "Sections/Announcement Barr",
  component: template,
  render: args => {
    const { blocks = [], ...settings } = args
    console.log(
      "args",
      renderTemplate(template, { section: { settings, blocks } })
    )
    return renderTemplate(template, { section: { settings, blocks } })
  },
}

export const AnnouncementBarr = {
  args: {
    blocks: [
      {
        type: "item",
        settings: {
          text: "Announcement",
        },
      },
    ],
  },
}
